### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by dstudzinski** [afitiskin/redux-saga-routines#1]
Hi,
I'm trying to use your package with create-react-app but I get ReferenceError.

```
routinesWatcherSaga.js:16 Uncaught ReferenceError: regeneratorRuntime is not defined
```
Do you know what the problem is and how to solve it?

EDIT: I've solved it by adding `import 'babel-polyfill'` in `index.js`. Not sure why it's needed. I thought generators are supported in create-react-app since version 0.2

**Comment by afitiskin** [comment]
You have to add babel-polyfill to your app to make it works

**Comment by aardito2** [comment]
Why is this closed?

The published module should work on its own without external dependencies - you've published the transpiled code without including the dependencies needed for it to run. 

I have my project set up so that I don't need to use babel-polyfill for generators to work, but it fails on this module because I am not running node_modules through babel (which shouldn't ever be necessary).

There should ideally be two versions of the module included in the published version: an es copy which is not transpiled, and a transpiled version that includes regeneratorRuntime.

**Comment by afitiskin** [comment]
Ok guys, I reopened the issue, and will add `regenerator-runtime` as a dependency for the module today, so transpiled version will work well. 
About es copy I will find solution a bit later (If you have time - PR is welcome)

**Comment by afitiskin** [comment]
Published version `1.1.1` to npm with 2 entry points: 
1. `main`: transpiled version (with babel-runtime as a peer dependency)
2. `jsnext:main`: es2015 version

**Comment by wellingtonamaralleitao** [comment]
Still not working...

**Comment by ambrons** [comment]
@wellingtonamaralleitao this type of error is typically solved by including `babel-polyfill` in your array of entries above your app entry.  Or at least anytime I've seen it that's how I've solved it.

Of course I'm making the assumption that you're using webpack.

https://babeljs.io/docs/plugins/transform-regenerator/

**Comment by wellyal** [comment]
We dicided to use another pattern to handle our sagas. Thanks though

**Comment by afitiskin** [comment]
@wellyal @svagi are you using common js version or es version? `regenerator-runtime` polyfill is included only in common js version and I'm not sure about adding it to es version... Any ideas?

**Comment by agriffis** [comment]
@afitiskin I just started using redux-saga-routines (an hour ago) with create-react-app and I'm hitting this problem. I've tried `yarn add babel-polyfill` and then `import 'babel-polyfill'` at the top of `index.js` but still hitting the same problem. If you have suggestions then I'd be happy to try them.

**Comment by agriffis** [comment]
@afitiskin This seems to fix it for me:

```patch
diff --git a/package.json b/package.json
index 88cc7de..dedc113 100644
--- a/package.json
+++ b/package.json
@@ -11,7 +11,6 @@
     "redux-form"
   ],
   "main": "dist/index.js",
-  "module": "es/index.js",
   "jsnext:main": "es/index.js",
   "devDependencies": {
     "babel-cli": "^6.24.1",
```

When the `"module"` field is present, then `import` uses it in favor over `"main"`

This seems related and it's where I got the idea, but I don't claim to fully understand the ramifications of including or excluding the `"module"` field: https://github.com/infernojs/inferno/issues/928

**Comment by agriffis** [comment]
@afitiskin also this seems relevant: https://github.com/webpack/webpack/issues/1979

**Comment by aardito2** [comment]
Adding `transform-runtime` to the `es` plugins in `.babelrc` should be the fix, since the `es` build is still transpiling generators to use it.

**Comment by afitiskin** [comment]
@aardito2 @agriffis included `babel-runtime` transform to ES version, updated package to `1.1.2`, please check if it works now.

**Comment by agriffis** [comment]
@afitiskin working here, thank you!
