### ISSUE TITLE
Calling routine doesn't dispatch any action

### ISSUE THREAD

**Issue by m-sadegh-sh** [afitiskin/redux-saga-routines#14]
I've upgraded to v2 and all of my actions were broken.

Changes I've made into my code is:

1. Use routinePromiseWatcherSaga instead of routinesWatcherSaga to add to saga middleware.
2. Use bindRoutineToReduxForm and pass created routine to it to create redux-form compatible handler.
3. Update mapDispatchToProps implementation to remove bindRoutineCreators and return routines directly as below:

```
function mapDispatchToProps(dispatch) {
    return {
        ...{ commandBarAddItemsRoutine },
        dispatch
    };
};
```

4. Replace any this.props.routine.trigger(payload) with this.props.routine(payload). (optional)

Before upgrading to v2, my codes works well. I've not updated other related packages like redux, redux-saga so I think the issue is related to this package.

**Comment by afitiskin** [comment]
Hi, may I see the code, that does not work: component, and saga?

**Comment by afitiskin** [comment]
If you use `bindRoutineToReduxForm` you do not need to pass bound routine thru `mapDispatchToProps`.

**Comment by m-sadegh-sh** [comment]
Ok here is it.


`//Routine and triggerer
import { put, call } from 'redux-saga/effects';
import { createRoutine, bindRoutineToReduxForm } from 'redux-saga-routines';

export const chooseLetterPreparingFindEmbeddedLetterIdRoutine = createRoutine('CHOOSE_LETTER_PREPARING_FIND_EMBEDDED_LETTER_ID');

export const chooseLetterPreparingFindEmbeddedLetterIdHandler = bindRoutineToReduxForm(chooseLetterPreparingFindEmbeddedLetterIdRoutine);

export function* chooseLetterPreparingFindEmbeddedLetterIdTrigger(action) {
    try {
        console.log(chooseLetterPreparingFindEmbeddedLetterIdRoutine.request, action);
        yield put(chooseLetterPreparingFindEmbeddedLetterIdRoutine.request());

        const response = yield call(wordService.findEmbeddedLetterId);

        yield put(chooseLetterPreparingFindEmbeddedLetterIdRoutine.success(response));
    } catch (error) {
        yield put(chooseLetterPreparingFindEmbeddedLetterIdRoutine.failure(error));
    } finally {
        yield put(chooseLetterPreparingFindEmbeddedLetterIdRoutine.fulfill());
    }
}`

`import { fork, takeLatest } from 'redux-saga/effects';

import { chooseLetterPreparingFindEmbeddedLetterIdRoutine, chooseLetterPreparingFindEmbeddedLetterIdTrigger } from './choose-letter-preparing.action';

export function* appWatcherSaga() {
    yield [
        ...,
        fork(takeLatest, chooseLetterPreparingFindEmbeddedLetterIdRoutine.TRIGGER, chooseLetterPreparingFindEmbeddedLetterIdTrigger),
        ....
    ];
}`

`Component usages

import { chooseLetterPreparingFindEmbeddedLetterIdRoutine } from '../actions/choose-letter-preparing.action';

export class ChooseLetterPreparingComponent extends React.Component {
    componentDidMount() {
        this.props.chooseLetterPreparingFindEmbeddedLetterIdRoutine(payload);
    }

    render() {
        return (
            <p>
                blah blah blah
            </p>
        );
    }
}

function mapStateToProps(state) {
    return { ... };
}

function mapDispatchToProps(dispatch) {
    return {
        ...{ chooseLetterPreparingFindEmbeddedLetterIdRoutine },
        dispatch
    };
};

export default withRouter(connect(mapStateToProps, mapDispatchToProps)(ChooseLetterPreparingComponent));
`

**Comment by afitiskin** [comment]
Problem is here:
```
function mapDispatchToProps(dispatch) {
    return {
        ...{ chooseLetterPreparingFindEmbeddedLetterIdRoutine },
        dispatch
    };
};
```

Try to change it with following:
```
function mapDispatchToProps = {
  chooseLetterPreparingFindEmbeddedLetterIdRoutine,
};
```

**Comment by m-sadegh-sh** [comment]
Thank you @afitiskin

**Comment by m-sadegh-sh** [comment]
@afitiskin If i need to this.props.dispatch to dispatch an action that is not in the form of routines, what I have to do?

```
function mapDispatchToProps(dispatch) {
    return {
        myRoutine,
        dispatch
    };
};
```

**Comment by afitiskin** [comment]
Use `bindActionCreators` from `redux` package as you do with simple action creators, or just manually dispatch result of routine call: `dispatch(myRoutine())`

**Comment by m-sadegh-sh** [comment]
@afitiskin As you told me, I have to write my mapDispatchToProps like below.

```
const mapDispatchToProps = {
  myRoutine,
};
```

Above result don't provide dispatch to this.props. If I use below, nothing will be dispatched.

```
function mapDispatchToProps(dispatch) {
    return {
        myRoutine,
        dispatch
    };
};
```

I've confused a little bit. Using [bindActionCreators](http://redux.js.org/docs/api/bindActionCreators.html) also requires this.props.dispatch.

**Comment by afitiskin** [comment]
As I see you do not know how `connect` works. Please read carefully docs of `react-redux`. 
You have 2 options:
1. Just not provide `mapDispatchToProps`. In this case your component will get `dispatch` as a prop. To dispatch routine action you need to do `this.props.dispatch(myRoutine())`
2. Use `bindActionCreators` from `redux`:
```
mapDispatchToProps = (dispatch) => ({
  ...bindActionCreators({
    myRoutine1,
    myRoutine2,
  }),
  dispatch,
});
```

If you pass an object to `mapDispatchToProps` as I recommend above, `react-redux` will use `bindActionCreators` internally to bind passed action creators.

And one more note: why you need both: bound action creators (or routines) and `dispatch`? I think you are doing something wrong...
