### ISSUE TITLE
Use routine as a promise

### ISSUE THREAD

**Issue by m-sadegh-sh** [afitiskin/redux-saga-routines#15]
Hi

I v1 calling routine directly returns a Promise and we used routine.then. But in this version routine itself is trigger action creator. [Here](https://github.com/afitiskin/redux-saga-routines/issues/6#issuecomment-325354910) you told something that is not correct at the moment.

In my case i should return a promise (to a third-party component). Thanks in advance for your suggestions dear @afitiskin 👍

**Comment by afitiskin** [comment]
See [redux-saga, redux-form, redux-saga-routines combo](https://github.com/afitiskin/redux-saga-routines#redux-saga-redux-form-redux-saga-routines-combo) in README. 

```javascript
import { createRoutine, bindRoutineToReduxForm } from 'redux-saga-routines';
export const myRoutine = createRoutine('SOME_ROUTINE');
export const myBoundRoutine = bindRoutineToReduxForm(myRoutine);
```

`submitFormHandler` is now the function that return a promise. It has following signature: 
```
(values, dispatch, props) => Promise
```

So, if you need to return promise to third-party component, do it like this:
```
someHandler() {
  const { dispatch } = this.props;
  const someDataYouNeedInYourSaga = { ... };
  const promise = myBoundRoutine(someDataYouNeedInYourSaga, dispatch);
  // ...
}
```

**Comment by afitiskin** [comment]
With last update I added `promisify` helper and `bindPromiseCreators` util to wrap routines in function that returns promise, bind that function to store's dispatch.
