### ISSUE TITLE
Wrong NPM latest tag?

### ISSUE THREAD

**Issue by plitex** [afitiskin/redux-saga-routines#17]
Hi,

Tag latest is pointing to 1.1.5, is it correct? Can we consider 2.0 as production ready? There is no info about state of 2.0 in README. Looking at the docs I understand 1.x is the OLD release and 2.0 should be used.

```bash
> $ yarn add redux-saga-routines                                                                                                                     ⬡ 8.7.0 [±master ●●]
yarn add v1.2.1
warning package.json: No license field
warning ../package.json: No license field
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
└─ redux-saga-routines@1.1.5
```

**Comment by afitiskin** [comment]
Yep, latest release was fix for v1... Should update latest tag for npm

**Comment by afitiskin** [comment]
Updated latest tag on NPM, so now `2.1.0` is installed by default. Also added `legacy` tag for latest v1 build (to use like `yarn add redux-saga-routines@legacy`)
