### ISSUE TITLE
Typescript: Cannot find name 'Generator'.

### ISSUE THREAD

**Issue by tonoslav** [afitiskin/redux-saga-routines#19]
I keep getting this error from typescript

```console
ERROR in [at-loader] ./node_modules/redux-saga-routines/src/index.d.ts:26:46
    TS2304: Cannot find name 'Generator'.
```

**Typescript:** 2.5.3
**redux-saga-routines:** 2.2.1

**Comment by afitiskin** [comment]
@LKay your help needed

**Comment by LKay** [comment]
@tonoslav Could you share your `tsconfig.json`'s compile flags? Make sure you have at least: `es2015.iterable` and `es2015.generator` in your `lib` and have `@types/node` installed.

**Comment by tonoslav** [comment]
Fixed, thank you

```js
{
    "compilerOptions": {
      ...
        "lib": [
            "dom",
            "es5",
            "scripthost",
            "es2015.generator"
        ]
    },
   ...
}
```
