### ISSUE TITLE
Call trigger directly from routine

### ISSUE THREAD

**Issue by mbektimirov** [afitiskin/redux-saga-routines#2]
As usage with `redux-form` is more rare than normal action triggering, why don't just extract promise to its own place and use routine to call `TRIGGER` action directly? This is a common approach to call actions in Redux and it will not drive to disambiguation with each action call. 
```js
const routine = payload => {
  routineParams.trigger(payload);
}

routine.promise = (data, dispatch) => {
  return new Promise((resolve, reject) => dispatch({
    type: PROMISE_ACTION,
    payload: {
      data,
      params: routineParams,
      defer: { resolve, reject },
    },
  }));
};
```

**Comment by afitiskin** [comment]
Good idea! Can you please make a pull request?

**Comment by afitiskin** [comment]
In version 2 routine by itself is a trigger action creator:
```javascript
expect(routine(payload)).to.deep.equal(routine.trigger(payload));
```
