### ISSUE TITLE
Slash instead of classic underline

### ISSUE THREAD

**Issue by onrige** [afitiskin/redux-saga-routines#20]
Hey. Thanks for great and very helpful tool first. I have a question. In previous version there was an underline between routine prefix and routine type. Why did you decide to change this with slash? I think it was more redux classic before.
https://github.com/afitiskin/redux-saga-routines/blob/master/src/createRoutine.js#L5

**Comment by afitiskin** [comment]
@onrige I prefer use slash instead of underscore cause slash works like a namespace separator while underscore is just a word separator. Also it is more difficult get duplicates of actions on new name notation:
```
// old version
const makePaymentRoutine = createRoutine('PAYMENT'); // not so good name for "make payment" action but it is possible to have such action
const makePaymentRequestAction = createAction('PAYMENT_REQUEST'); // also not perfect name for "request payment" action, possible as well
expect(makePaymentRoutine.REQUEST).toEqual(makePaymentRequestAction.toString()); // true – so we got a name collision
```

**Comment by onrige** [comment]
I don't understand your example, sorry. If we change underscore with slash in it - nothing will change. Or maybe you talk about name collision with redux-actions library in this case? If so - yes, it will be, but...what's next? :)

**Comment by afitiskin** [comment]
For me `/` – is a good namespace separator. Basically with every routine you get an action type namespace, contains 5 action types:
```
const routine = createRotuine('App/MyModule/SEND_PAYMENT');

// now you have:
// App/MyModule/SEND_PAYMENT/TRIGGER
// App/MyModule/SEND_PAYMENT/REQUEST
// App/MyModule/SEND_PAYMENT/SUCCESS
// App/MyModule/SEND_PAYMENT/FAILURE
// App/MyModule/SEND_PAYMENT/FULFILL

// imagine that your payment system has more then 4 basic routine stages:
// e.g. REQUEST -> TRANSACTION_VALIDATION -> AWAITING_CONFIRMATION -> CONFIRMED -> SUCCESS -> FULFILL

// it is more useful to have all these action types in one namespace:
// App/MyModule/SEND_PAYMENT/TRANSACTION_VALIDATION
// App/MyModule/SEND_PAYMENT/AWAITING_CONFIRMATION
// App/MyModule/SEND_PAYMENT/CONFIRMED

// instead of:
// App/MyModule/SEND_PAYMENT_TRANSACTION_VALIDATION
// because last one can mean that you are sending validation (of payment transaction) instead of its real meaning...
```
I wish last example will help you understand why I decided to change `_` with `/` :)

**Comment by onrige** [comment]
Yes, it has sense, but why don't just separate such logic in this case? Any new feature must have his own actions/reducer/etc I think (and it sounds like this from redux creator, Dan Abramov). So you wont need to create such actions like `App/MyModule/SEND_PAYMENT/TRANSACTION_VALIDATION` o_O

**Comment by victordidenko** [comment]
I learned, that `handleActions` could have recursive structure too, and by default it combines keys with `/`, so this makes this library perfectly compatible with it.
It could be perfectly compatible, **BUT** `routine.toString()` returns PREFIX/TRIGGER, not just PREFIX.

I created PR #33 to fix that.

@afitiskin could you assist here?

**Comment by afitiskin** [comment]
In latest version you are able to create your own routine creator, see [Creating your own routines ](https://github.com/afitiskin/redux-saga-routines#creating-your-own-routines) in README
