### ISSUE TITLE
bindPromiseCreators is not exported

### ISSUE THREAD

**Issue by mshick** [afitiskin/redux-saga-routines#21]
Was attempting to use the code examples and noticed that `bindPromiseCreators` is not being exported from the module. I've temporarily imported `src/bindPromiseCreators.js` and it works as expected.

**Comment by afitiskin** [comment]
Thank you! I forgot to export it... Now it is fixed. Bumped version to `2.2.2`

**Comment by afitiskin** [comment]
@mshick may I close the issue?

**Comment by mshick** [comment]
@afitiskin Updated yesterday — looks good to me! Thanks.
