### ISSUE TITLE
Adding meta field: where this action come from

### ISSUE THREAD

**Issue by linonetwo** [afitiskin/redux-saga-routines#24]
For a better debugging experience, I hope there is a field in action's meta field, telling me where this action comes from.

Likes
```js
{
  type: 'getCompanyIDs_SUCCESS',
  payload: {
    IDs: [
      '836012',
      '833150',
      '838835',
      '430255',
      '833946'
    ],
    rowsInAPage: 9
  },
  meta: {
    fromSaga: 'getCompanyIDs'
  }
}
```
So I can easily know this action comes from ```getCompanyIDs()```, not other saga likes ```starUpJobsSaga()``` or so.

**Comment by afitiskin** [comment]
Since `redux-saga-routines` was build on top of `redux-actions` you can use third parameter (`metaCreator`) to achieve this:
```
const getCompanyIDs = createRoutine('getCompanyIDs', null, () => ({ .fromSaga: 'getCompanyIDs' }))
```

**Comment by linonetwo** [comment]
Thanks, with that, I think I can mark some critical action by hand.

(I searched about how I could get function name inside a generator function, only to find some old stuff)

**Comment by linonetwo** [comment]
Wait, what if I export created routines, I can't pass ```metaCreator``` on the fly? Can I do something like currying ```createRoutine``` ?

**Comment by afitiskin** [comment]
I'm not sure what you are going to achieve, so I can't recommend something

**Comment by linonetwo** [comment]
Like I have an ```changeCompanyCodeForDiffAction``` 
that will be ```yield put``` by  ```function* handleURIChange()```  and  ```function* gotoNextCompanyCode()``` and several other sagas.

I think I should pass meta info when I put it, instead of creating several routines for every saga.

**Comment by mshick** [comment]
@afitiskin agreed — I think it would be helpful to support passing metadata when the routine is triggered. 

An example pattern might be passing meta as a second param:

```
routine.trigger(payload, meta)
```

A simple case, maybe I want to keep my payloads clean, and pass necessary info for acting on the payload beside it:

```
this.props.updateUser(
  {firstName: 'foo'}, 
  {userId: 'abc123'}
);
```

Or, more complicated, maybe I want to pass special data for an analytics middleware alongside my payload, like this:

```
this.props.updateUser(
  {firstName: 'foo'}, 
  {
    analytics: {
      event: 'userUpdated',
      payload: {userId: 'abc123'}
  }
);
```

The reason for treating it this way (as opposed to creating separate routines) is that we want to tie our analytics to the actual event that caused the update, and not rely on a more tenuous connection between events.
