### ISSUE TITLE
Resolve Promisified Routine after Fulfill

### ISSUE THREAD

**Issue by ckeeney** [afitiskin/redux-saga-routines#27]
Suppose I want to filter actions to avoid fetching data that I already have in the store.  I dispatch a `fulfill` but that doesn't resolve the promise, since I never fired `success` or `failure` action.  I have reducers listening for `success` and `failure` for an action, so I can't really fire those actions unless I actually made a request to the server.  

It seems that dispatching a `fulfill` should resolve the promise wrapping the routine.

From the [Filtering actions](https://github.com/afitiskin/redux-saga-routines#filtering-actions) section of the README:
```js
let counter = 0;
function* handleTriggerAction() {
  if (counter++ % 2 === 0) {
    // perform API request only on odd calls
    yield call(fetchDataFromServer);
  }

  // trigger fulfill action to finish routine lifecycle on every click
  yield put(fetchData.fulfill());
}
```

And from the [Wrap a routine into a promise](https://github.com/afitiskin/redux-saga-routines#wrap-routine-into-promise) section:
> to resolve promise you need to dispatch myRoutine.success(successPayload) action, successPayload will be passed to resolved promise
> if  myRoutine.failure(failurePayload) is dispatched, promise will be rejected with failurePayload.

  If the example for filtering actions is wrapped in a promise, promises for skipped actions never resolve.

**Comment by ckeeney** [comment]
If this change should be made, is it as simple as adding a fulfill watcher to the race [here](https://github.com/afitiskin/redux-saga-routines/blob/99722fad0b07cd2467c92899fe6de07a1142cde1/src/routinePromiseWatcherSaga.js#L21-L22)?

**Comment by ckeeney** [comment]
I copied and pasted the `routinePromiseWatcherSaga` into my saga and made the above change.  It seems to work well.  
I'm happy to open a pull request for this change.  However, I'm not sure whether a `fulfill` should call the `resolve` or `reject` function.  I'm not sure either choice is intuitive.

**Comment by afitiskin** [comment]
It's very uncommon case to use both: promise and filtering. Could you please give more information about your task? 
I'm not going to change behaviour of fulfill – it should NOT do something with promise, promise can  be resolved or rejected only using resolve and reject actions (because other behaviour is very specific and is not intuitive).
And, of cource, filtering in your case can be done in reducer.

**Comment by ckeeney** [comment]
Thanks so much for replying.

I don't mind you not changing the behavior of fulfill.  Having one extra saga watcher in my repo is not a big deal.

However, I do want to make sure I'm not doing something wrong.

> It's very uncommon case to use both: promise and filtering. Could you please give more information about your task?


I am filtering actions to avoid fetching data I already have in redux.  For example, if someone browses to `/article/slug-one` and I already have the `slug-one` data in redux, I don't need to fetch this data.  If I filter in the reducer, then requests will have actually been made but I throw away the data.  I don't think the reducer is the correct place for filtering.  

I'm using [nextjs](https://github.com/zeit/next.js/#fetching-data-and-component-lifecycle).  In their docs they have the following demo for waiting on data to populate before rendering:

```js
const Page = ({ stars }) =>
  <div>
    Next stars: {stars}
  </div>

Page.getInitialProps = async ({ req }) => {
  const res = await fetch('https://api.github.com/repos/zeit/next.js')
  const json = await res.json()
  return { stars: json.stargazers_count }
}

export default Page
```

I do something similar in my own components:

```js
class ArticlePage extends Component {
    static async getInitialProps({query: { slug }, req, store, }) {
        const creators = bindPromiseCreators({
            fetchArticlePromiseCreator,
        }, store.dispatch);

        await creators.fetchArticlePromiseCreator(slug);
        return {
            article: selectSingleArticle(store.getState(), slug)
        };
    }
    // ...
```

My sagas look like this:

```js
function* triggerArticle (api, {payload}) {
    const article = yield select(selectSingleArticle, payload);
    if (! article.content) {
        yield call(requestArticle, api, {payload});
    }
    yield put(fetchArticleActions.fulfill());
}

function* requestArticle (api, action) {
    console.log(action);
    yield put(fetchArticleActions.request());
    const response = yield call(api.getArticle, action.payload);
    if (response.ok) {
        const normalized = normalize(response.data, articleSchema);
        yield put(fetchArticleActions.success(normalized));
    } else {
        yield put(fetchArticleActions.failure(response));
    }
}

export default function* articleSagas(cmsClient) {
    yield all([
        takeEvery(fetchArticleActions.TRIGGER, triggerArticle, cmsClient),
    ]);
}
```

The filtering of sagas and the usage of promises to wait for data to populate seem like unrelated ideas.  My promises call `resolve` if `fulfill` is dispatched before `success` or `failure`.  This works for my uses because if the action is `fullfill`ed, then I know the data is in redux.

However, I'm fairly new to both sagas and promises and I'm inclined to defer to your expertise here.  Is there a reason things should not be done this way other than that it is uncommon?

**Comment by afitiskin** [comment]
Okay, I got the idea. You can do following in your saga:

```javascript
function* triggerArticle (api, {payload}) {
  const article = yield select(selectSingleArticle, payload);
  if (! article.content) {
    yield call(requestArticle, api, {payload});
  } else {
    // use data of loaded article from redux store to fulfill promise
    yield put(fetchArticleActions.success(article.content));
  }
  yield put(fetchArticleActions.fulfill());
}
```

**Comment by ckeeney** [comment]
I suppose that works, though it does unnecessarily run the reducers for processing `article.content`.

I think I am just going to close this issue.  There is some discussion here for anyone that comes searching for it, and if you don't think we should resolve the promise on fulfill dispatch, there is not really anything to do in this issue.

Like I said, having one extra saga watcher in my code is not a big deal.  For completeness, I have included the entire saga watcher below.  All I've done is add a `take(routine.fulfill)` to the race and call resolve if that comes back first.

```js
import { takeEvery, take, race, put, call, all } from 'redux-saga/effects';
import {ROUTINE_PROMISE_ACTION} from "redux-saga-routines";

const getPayload = (data) => (data && data.payload) || data;

export function* handleRoutinePromiseAction(action) {
    const {
        payload,
        meta: {
            routine,
            reduxFormCompatible,
            defer: {
                resolve,
                reject,
            },
        },
    } = action;

    const [ {success, failure, fulfill} ] = yield all([
        race({
            success: take(routine.SUCCESS),
            failure: take(routine.FAILURE),
            fulfill: take(routine.FULFILL),
        }),
        put(routine.trigger(payload)),
    ]);

    if (success || fulfill) {
        yield reduxFormCompatible ? call(resolve) : call(resolve, getPayload(success));
    } else {
        yield call(reject, getPayload(failure));
    }
}

export default function* routinePromiseWatcherSaga() {
    yield takeEvery(ROUTINE_PROMISE_ACTION, handleRoutinePromiseAction);
}

```
