### ISSUE TITLE
[...effects] has been deprecated in favor of all(...effects])

### ISSUE THREAD

**Issue by spawner999** [afitiskin/redux-saga-routines#3]
Should update code in routinesWatcherSaga.js to reflect changes introduced in saga's  [0.15.0 release](https://github.com/redux-saga/redux-saga/releases/tag/v0.15.0).

Currently throws this warning: 
<img width="624" alt="screen shot 2017-05-13 at 6 53 03 pm" src="https://cloud.githubusercontent.com/assets/14125641/26027388/71917d42-380d-11e7-9945-93c4971561be.png">

**Comment by afitiskin** [comment]
Thank you for report, will fix this warning in next version

**Comment by reidpd** [comment]
Is there any movement on this issue?

**Comment by reidpd** [comment]
#9

**Comment by afitiskin** [comment]
Closed via #9
