### ISSUE TITLE
Please publish the repo as "pre-compiled"

### ISSUE THREAD

**Issue by maorshabo** [afitiskin/redux-saga-routines#31]
Hi,
I'm using create-react-app to create my app, and then I tried to build the app I get this error:
```
react-scripts build

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

        ./node_modules/redux-saga-routines/src/routinePromiseWatcherSaga.js:4 

Read more here: http://bit.ly/2tRViJ9
```
Thanks!

**Comment by afitiskin** [comment]
@maorshabo Why did you close the issue?

**Comment by maorshabo** [comment]
Because it was my bad, the package is compiled to es. And I imported files directly from /src directory which cause the error I've mentioned above

**Comment by afitiskin** [comment]
Ok :)
