### ISSUE TITLE
V2 doesn't trigger actions

### ISSUE THREAD

**Issue by danicr83** [afitiskin/redux-saga-routines#32]
Hello afitiskin!
Maybe I'm doing something wrong but following instructions you posted in README, actions doesn't seems to be triggered. Is it necessary some additional configuration while creating the store with middlewares? If so could you please integrate the README with that? Thank you sir.

**Comment by afitiskin** [comment]
@danicr83 may you please provide some code of the component that trigger routine?

**Comment by McRipper** [comment]
I'm having the same issue, the missing example is when we have standard actions to dispatch:

`function mapDispatchToProps(dispatch) {
  return {
    _changeRoute: (url) => dispatch(push(url)),
    purchase, // <- this is the routine that is not triggered
  }
}`

**Comment by afitiskin** [comment]
As you can see in the README my `mapDispatchToProps` is an Object while your `mapDispatchToProps` is a function. So inside `mapDispatchToProps` function you have to bind routine to dispatch manually or using `bindActionCreators`.

**Comment by afitiskin** [comment]
@danicr83 @McRipper did my comment help you?
