### ISSUE TITLE
onSubmitActions supports

### ISSUE THREAD

**Issue by codelego** [afitiskin/redux-saga-routines#37]
Are there any way to support similar method

```js
import { onSubmitActions } from 'redux-form-submit-saga'

export reduxForm({
   form: 'FORM_LOGIN',
   onSubmit: onSubmitAction('FORM_LOGIN')
})()
```

**Comment by afitiskin** [comment]
Please read the README carefully. [This section](https://github.com/afitiskin/redux-saga-routines#redux-saga-redux-form-redux-saga-routines-combo) has explanation how this library works with `redux-form`.

First of all, create routine and make submit handler for it:
```javascript
// routines.js

import { createRoutine, bindRoutineToReduxForm } from 'redux-saga-routines';
export const submitFormRoutine = createRoutine('SUBMIT_MY_FORM');
export const submitFormHandler = bindRoutineToReduxForm(submitFormRoutine);
```

Then, pass it to the `redux-form` as submit handler:
```javascript
reduxForm({
   form: 'FORM_LOGIN',
   onSubmit: submitFormHandler,
})(YourFormComponent)
```

So, submitting the form will trigger `SUBMIT_MY_FORM_TRIGGER` action that can be handled in your sagas.

**Comment by afitiskin** [comment]
@codelego may I close the issue?
