### ISSUE TITLE
Difference between TRIGGER and REQUEST?

### ISSUE THREAD

**Issue by jmtoung** [afitiskin/redux-saga-routines#43]
Hi, great library first of all. Really nice. However I have a potentially naive question. What's the difference between TRIGGER and REQUEST? After reading your examples, particularly `Example: fetching data from server`, it seems that the two action types are redundant based on the following observations:

1. There is no case in the reducer to deal with REQUEST.

```
export default function exampleReducer(state = initialState, action) {
  switch (action.type) {
    case fetchData.TRIGGER:
      return {
        ...state,
        loading: true,
      };
    case fetchData.SUCCESS:
      return {
        ...state,
        data: action.payload,
      };
    case fetchData.FAILURE:
      return {
        ...state,
        error: action.payload,
      };
    case fetchData.FULFILL:
      return {
        ...state,
        loading: false,
      };
    default:
      return state;
  }
}
```

2. In the saga, the trigger seems to want to just start a new request to the api. There is a `yield put(fetchData.request())`, but as pointed out above, the reducer doesn't do anything with that dispatched action.

```
function* requestWatcherSaga() {
  // run fetchDataFromServer on every trigger action
  yield takeEvery(fetchData.TRIGGER, fetchDataFromServer)
}

function* fetchDataFromServer() {
  try {
    // trigger request action
    yield put(fetchData.request());
    // perform request to '/some_url' to fetch some data
    const response = yield call(apiClient.request, '/some_url');
    // if request successfully finished
    yield put(fetchData.success(response.data));
  } catch (error) {
    // if request failed
    yield put(fetchData.failure(error.message));
  } finally {
    // trigger fulfill action
    yield put(fetchData.fulfill());
  }
}

```

**Comment by afitiskin** [comment]
Sometimes it really useful to know if request to API sent, to collect some stat. For simple cases it looks redundant, by for consistency I prefer to trigger all routines actions.
