### ISSUE TITLE
Broken Typescript definitions

### ISSUE THREAD

**Issue by LKay** [afitiskin/redux-saga-routines#46]
The definitions that got merged yesterday completely changed the way actions are handled. I'm not against the changes, but this is a __BREAKING CHANGE__ and should be only introduced with major version of the library (if you follow semver).

**Comment by LKay** [comment]
Related to #47 #48

**Comment by alexey-pelykh** [comment]
It hasn't changed how they are handled at all, only changed the declaration's to be more specific

**Comment by alexey-pelykh** [comment]
(Indeed, #41 is broken due to lost change, #45 is a hotfix for that)

Regarding the breaking change - the behavior itself wasn't changed, only the declarations, to match `@types/redux-actions@2.3.0`

**Comment by afitiskin** [comment]
Since I'm not using TypeScript I can't verify PRs related to type definitions. So, if they broke something for somebody and there is no maintainer who can verify it I'm going to remove type definitions from the repo. If you want to maintain them in the repo, let's organise it. Other case: create separated repo with type definitions for `redux-saga-routines`.

**Comment by afitiskin** [comment]
And I'm not agree with the point that "changing type definitions is the breaking change". It's not related to core of the library, so it can't broke anything that depends on the library

**Comment by alexey-pelykh** [comment]
(noone asked, yet :) ) I'd support moving type definitions to `@types` repo, at least there we'll have to cover them with tests, so definitely there would be a benefit from it.

**Comment by alexey-pelykh** [comment]
(and super-sorry for loosing that change, my bad)

**Comment by afitiskin** [comment]
Does #45 fixes the problem?

**Comment by afitiskin** [comment]
I've also deprecated version "2.2.4"

**Comment by afitiskin** [comment]
@LKay is your problem still reproducing with v2.2.5?

**Comment by afitiskin** [comment]
@LKay, @janstrohbeck, @alexey-pelykh I need your help to decide: should I keep type definitions in the repo or should I remove it?

Option 1: I keep type definitions in the repo. But we choose a maintainer who will keep it up to date and will take care about all issues and MRs related to them.

Option 2: I remove type definitions from the repo. You can create separated repo for them. There is https://www.npmjs.com/package/@types/redux-saga-routines that is deprecated at the moment.

**Comment by alexey-pelykh** [comment]
Technically, that's the same option - the only difference where type definitions would be maintained. I'd vote for Option 2 - that way even if package definition maintainer won't answer, a `@types` maintainers will take care of that (like in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25286 case)

**Comment by afitiskin** [comment]
So, in version 3.0.0 type definitions will be removed from the repo.

**Comment by alexey-pelykh** [comment]
Please ping me when/if you'll need help in migration to `@types`

**Comment by afitiskin** [comment]
@alexey-pelykh I have no plans related to `@types` since I'm not using typescript

**Comment by darewreck54** [comment]
Does this mean that there is no typescript support for using this library?

**Comment by alexey-pelykh** [comment]
Not by the library author, and as far as I can see, nobody introduced that package to `@types`. 

@afitiskin I've missed your message, very sorry. Please bring me up to speed - in 3.0.0 version you've removed the type definitions, so somebody should grab latest type definitions and upgrade it to 3.x branch, yet in `@types` or should those be written from scratch?

**Comment by alexey-pelykh** [comment]
Please give this one a try https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34730 @darewreck54 @LKay
