### ISSUE TITLE
Question regarding promisifyRoutine

### ISSUE THREAD

**Issue by stefanfrede** [afitiskin/redux-saga-routines#49]
I'm wondering if this should work and I'm doing something wrong, or if it is simply not working this way:
```js
itemsRoutinePromiseCreator(payload, store.dispatch)
  .then(
    successPayload => console.log('success :)', successPayload),
    failurePayload => console.log('failure :(', failurePayload),
  );
```
I'm using this in a plain JS file without any framework and I get no response whatsoever. The only thing is a `@@redux-saga-routines/PROMISE` in the dev tools.

My `itemsRoutine` where the `itemsRoutinePromiseCreator` is based on works fine:
```js
store.dispatch(itemsRoutine.request(payload)
```

**Comment by afitiskin** [comment]
Did you run `routinePromiseWatcherSaga`?  See first code block in [Wrap routine into promise](https://github.com/afitiskin/redux-saga-routines#wrap-routine-into-promise) section of Readme

**Comment by stefanfrede** [comment]
Thanks a ton, `routinePromiseWatcherSaga` solved it, but now I have another question. Now I get `ITEMS/TRIGGER`, but I would like to receive `ITEMS/REQUEST`. Is this possible?

**Comment by afitiskin** [comment]
Take `TRIGGER` In your saga and put `REQUEST` manually according to examples from readme

**Comment by stefanfrede** [comment]
Will do. Thanks again.
