### ISSUE TITLE
Direct call to failure() function throws an error

### ISSUE THREAD

**Issue by rhenderson07** [afitiskin/redux-saga-routines#5]
### Documentation Example
The documentation shows the following example code (comments omitted) for requesting data from a server:

	function* fetchDataFromServer() {
	  try {
		yield put(fetchData.request());
		const response = yield call(apiClient.request, '/some_url');
		yield put(fetchData.success(response.data));
	  } catch (error) {
		yield put(fetchData.failure(response.error));
	  }
	}

Notice that the call to `failure` references `response`, which is not currently in scope. I presumed this to be a typo.

### Modified Example
With slight adjustments, I get the following segment:

	function* fetchDataFromServer() {
	  try {
		yield put(fetchData.request());
		const response = yield call(apiClient.request, '/some_url');
		yield put(fetchData.success(response.data));
	  } catch (error) {
		yield put(fetchData.failure(error.message));
	  }
	}

Within the catch block, the call to routine.failure results in a new, uncaught error.

I cannot seem to find any way of calling `put`  with the `failure` method without throwing an error. This does not occur when calling `put` on any of the other routine methods.

Is this a bug, or am I misunderstanding the proper way of calling routine.failure()?

Thank you.

**Comment by afitiskin** [comment]
@rhenderson07 Could you provide a description of "new, uncaught error"?

**Comment by rhenderson07** [comment]
Disregard.

While trying to reproduce the error, I found that my component was not triggering the routine correctly.

My component was calling `this.props.fetchData()` rather than `this.props.fetchData.trigger()`.

The incorrect call appears to work correctly when the routine is successful, but results in an uncaught error when the `failure` function is called. 

The error produced reads simply "Uncaught (in promise) <Your error message>".

Expanding the trace gets a bit confusing, as it gets into the inner workings of redux-saga:
```
| runCallEffect | @ | proc.js:503
| runEffect | @ | proc.js:431
| next | @ | proc.js:312
| currCb | @ | proc.js:385
| checkEffectEnd | @ | proc.js:599
| chCbAtIdx | @ | proc.js:614
...
```

Sorry about the waste of time.

Thanks for the quick reply.
