### ISSUE TITLE
TS support?

### ISSUE THREAD

**Issue by theKashey** [afitiskin/redux-saga-routines#50]
Any reasons to drop it?
Any chances to have it back?

**Comment by afitiskin** [comment]
IMO the best way is to have separated TS-specific package with all TS stuff and TS maintainer. TS developers may install 2 packages (code and types). JS developers will not be affected at all, and will not have dead files in their `node_modules`. 

There is [a package with types for the library](https://www.npmjs.com/package/@types/redux-saga-routines), but it is deprecated at the moment> I think it is possible to restore it.

**Comment by afitiskin** [comment]
Sorry, but no more TS support since version 3.
