### ISSUE TITLE
Why is payloadCreator shared across all actions?

### ISSUE THREAD

**Issue by abhikp** [afitiskin/redux-saga-routines#51]
Is there a way to overload the payloadCreator for a specific action?

In my situation, TRIGGER, SUCCESS, and FAILURE expect different payloads and I'd like the payloadCreators to reflect that.

**Comment by afitiskin** [comment]
Yep, I experienced the same problem in my last project, so in next version I will add support for different payload creators for different action types. If you would like to help me with PR, you are welcome!

**Comment by afitiskin** [comment]
In [version 3.1.0](https://github.com/afitiskin/redux-saga-routines/releases/tag/3.1.0) you are able to do following:

```
const myRoutine = createRoutine('SOME/PREFIX', {
  trigger: (payload) => payload * 2,
  request: (payload) => payload * 3,
  success: (payload) => payload * 4,
  failure: (payload) => payload * 5,
  fulfill: (payload) => payload * 2,
}, {
  trigger: () => { info: 'trigger action meta' },
  request: () => { info: 'request action meta' },
  success: () => { info: 'success action meta' },
  failure: () => { info: 'failure action meta' },
  fulfill: () => { info: 'fulfill action meta' },
})
```
