### ISSUE TITLE
Error with new Create-react-app version 2

### ISSUE THREAD

**Issue by rtorcato** [afitiskin/redux-saga-routines#52]
With create-react-app version 2 there is an error with this library

Module not found: Can't resolve '@babel/runtime/core-js/object/assign'

This issue is probably because you are using beta version of babel in your library.

**Comment by afitiskin** [comment]
Thank you for the feedback, please check updated [version 3.1.1](https://github.com/afitiskin/redux-saga-routines/releases/tag/3.1.1)

**Comment by rtorcato** [comment]
fixed thank you
