### ISSUE TITLE
Extend createRoutine with additional types

### ISSUE THREAD

**Issue by shapkarin** [afitiskin/redux-saga-routines#56]
I like that package but I want to extend stages if I need so I create [that fork](https://github.com/shapkarin/redux-saga-routines/commit/fa8fafcccfb1b99c8524b60e55c401eaf44dae7e). 
To use it like:

```js
import { createRoutine } from 'redux-saga-routines';

const user = createRoutine('user', { types: ['SOME'] });
```

But it needs to change second arg to obj. 

Maybe better is add some extend util like:
```js
import { createRoutine, extendRoutine }  from 'redux-saga-routines';

const user = extendRoutine(createRoutine('user'), ['SOME']);
```

I'll try to implement `extendRoutine` later to not change an API and test

---

UPDATE: Has PR with `createCustumRoutine(stages, payload, meta)` and `createExtendedRoutine(stages, payload, meta)`

**Comment by shapkarin** [comment]
Check PR
```
import { createRoutine, extendRoutine }  from 'redux-saga-routines';

const user = extendRoutine(createRoutine('user'), ['SOME']);
```

**Comment by shapkarin** [comment]
I decided to create `extendRoutine` instead of change `createRoutine` API

**Comment by shapkarin** [comment]
I decided to create `extendRoutine` instead of change `createRoutine` API. Check PR

**Comment by afitiskin** [comment]
I'd like to see the use case of proposed changes. May you attach some code examples?

**Comment by shapkarin** [comment]
I just don't like that at some components I can use routine like https://github.com/shapkarin/shapkarin.me/tree/master/src/Pages/Github
but in some https://github.com/shapkarin/shapkarin.me/tree/master/src/Pages/Projects I must to add custom types (`TOGGLE_PROJECT_INFO`) and create custom actions. 

But as I can see action function name will be just lowercased from `type` but for that change better is add toCamelCase.

**Comment by afitiskin** [comment]
I prefer to use `createAction` from [`redux-actions`](https://redux-actions.js.org/) for this use cases. It is also very useful to organise reducers using `handleActions` instead of switch-case.

**Comment by shapkarin** [comment]
Ok

**Comment by shapkarin** [comment]
`handleActions` is great, but I don't like to have separate variable (with `createAction`) from routine also with the same `type` prefix. Let me know if you can add that.

**Comment by shapkarin** [comment]
Just let me know if you OK with that feature and next I’ll try to implement it better, add more test and docs. It feels wrong to have some with actions and types about the same entity outside of routine.

**Comment by afitiskin** [comment]
I think we can make creator function `createRoutineCreator(stages)` and `createRoutine` will be built on top of that (the result of calling `createRoutineCreator` with default stages)

**Comment by shapkarin** [comment]
OK. Maybe `createRoutineCreator(typePrefix, stages)`. I can add that soon.

**Comment by afitiskin** [comment]
I think you did not get my idea. `createRoutineCreator` is a function that return `createRoutine` function. 

```
import { createAction } from 'redux-actions';
import defaultRoutineStages from './routineStages';

const isFunction = value => typeof value === 'function';

const getCreatorForType = (type, creator) => {
  if (!creator) {
    return creator;
  }
  if (isFunction(creator[type])) {
    return creator[type];
  }
  if (isFunction(creator[type.toLowerCase()])) {
    return creator[type.toLowerCase()];
  }
  if (isFunction(creator)) {
    return creator;
  }
  return undefined;
};

export function createRoutineCreator(routineStages) {
  return function createRoutine(typePrefix, payloadCreator, metaCreator) {
    const createActionCreator = (type) => createAction(`${typePrefix}/${type}`, getCreatorForType(type, payloadCreator), getCreatorForType(type, metaCreator));

    return routineStages.reduce(
      (result, stage) => {
        const actionCreator = createActionCreator(stage);
        return Object.assign(result, {
          [stage.toLowerCase()]: actionCreator,
          [stage.toUpperCase()]: actionCreator.toString(),
        });
      },
      createActionCreator(routineStages[0])
    );
  }
}

export default createRoutineCreator(defaultRoutineStages);
```

So, no we have unchanged `createRoutine` that works the same way as before, and also we have `createRoutineCreator` that can be used to create your own routine creator:

```
const createToggleRoutine = createRoutineCreator(['SHOW'], ['HIDE']);
const myToggleRoutine = createToggleRoutine('SOME_PREFIX');

myToggleRoutine.SHOW === 'SOME_PREFIX/SHOW';
myToggleRoutine.HIDE === 'SOME_PREFIX/HIDE';

myToggleRoutine.show(payload, meta) === { type: 'SOME_PREFIX/SHOW', payload, meta };
myToggleRoutine.hide(payload, meta) === { type: 'SOME_PREFIX/HIDE', payload, meta };
```

**Comment by afitiskin** [comment]
Will my solution solve your problem?

**Comment by shapkarin** [comment]
Yes, thanks, I'll change PR soon.

**Comment by shapkarin** [comment]
I just reproduced something like that https://github.com/shapkarin/extend-saga-routines and didn't got what you suggest. 
Yours solution is fine, I'll make it soon.

P.S. I'll freeze and deprecate my package after we add `createRoutineCreator`

**Comment by afitiskin** [comment]
`extendRoutine` looks like a tweak and will produce code duplicates in your application's code.

For example, in some module you need to extend your routine:
```javascript
// someContainer/routines.js
const routine = extendRoutine(createRoutine('PREFIX'), ['SOME', 'MORE', 'STAGES']);
```

When you need to use same extension in other module for another routine, you have to copy and paste same extension for another routine:

```javascript
// anotherContainer/routines.js
const routine2 = extendRoutine(createRoutine('PREFIX2'),  ['SOME', 'MORE', 'STAGES']);
```

And again, and again and again in other containers...

My solution:

```
// utils/createExtendedRoutine.js
export default createRoutineCreator(['SOME', 'MORE', 'STAGES']);

// someContainer/routines.js
import createExtendedRoutine from '../utils/createExtendedRoutine.js';
const routine = createExtendedRoutine('PREFIX');

// anotherContainer/routines.js
import createExtendedRoutine from '../utils/createExtendedRoutine.js';
const routine = createExtendedRoutine('PREFIX2');
```

**Comment by shapkarin** [comment]
Sure, I just inform you man :-)

**Comment by shapkarin** [comment]
Create PR, please review, forgot about docs, I'll add it later too

**Comment by shapkarin** [comment]
add example to docs

**Comment by shapkarin** [comment]
I updated PR, and now it don't has all that breaking changes. I'll add docs soon. 
All conversations are at PR :octocat:

**Comment by afitiskin** [comment]
I decided to exclude `createExtendedRoutine` and `createCustomRoutine` from the package, but it's just 5 lines of code, that can be done in your app:

```javascript
import { creteRoutineCreator, routineStages } from 'redux-saga-routines';
export const createCustomRoutine = (typePrefix, stages, payloadCreator, metaCreator) => creteRoutineCreator(stages)(typePrefix, payloadCreator, metaCreator);
export const createExtendedRoutine = (typePrefix, stages, payloadCreator, metaCreator) => creteRoutineCreator(routineStages.concat(stages))(typePrefix, payloadCreator, metaCreator);
```

Thank you for you idea and help with implementation, and sorry for long delay.
