### ISSUE TITLE
Would it be useful for trigger to return promise

### ISSUE THREAD

**Issue by alexhayes** [afitiskin/redux-saga-routines#6]
Perhaps I'm not understanding something but I'd really like to do something like the following;

```javascript
import { myRoutine from './routines';

class MyView extends React.Component {
    static mapDispatchToProps = dispatch => ({
        ...bindRoutineCreators({ myRoutine }),
    });

    onClick() {
        this.props.myRoutine.trigger().then(() => { ... });
    }

    ...
    ...
}
```

As in, I'd really like to get the promise back when I call `trigger` so I can do something if it's successful (or fails).

Is this possible but I'm just trying to do things the wrong way?

**Comment by afitiskin** [comment]
Trigger is an action creator, so it is only return an action, that have to be dispatched. I see only one reason why you need promises with `redux` – it is a promises for validation in `redux-form`. There is an example for this case in README

**Comment by alexhayes** [comment]
Apart from the fact that I also find this extremely useful outside of redux-form I actually want to do this;

1. User enters some data (in redux-form).
2. User presses submit.
3. Post sent to server which returns `201`.
4. Redirect the user to the newly created thing.

Ideally I'd like to do the redirect in my view/component once the `.success()` is called but I'm not exactly sure how to do it here.

I can of course push to the history in the async function that contains `yield put(routine.success(response));` but that seems a little like bad design.

**Comment by afitiskin** [comment]
Preffered way to this is to use`push` action creator from `react-router-redux` in your saga:
```
import { call, put, takeEvery } from 'redux-saga/effects';
import { push } from 'react-router-redux';

function* goToItem(item) {
  yield put(push(`/item/${item.id}`));
}

function* createSomethingSaga(action) {
  try {
    yield put(routine.request());
    const response = yield call(apiCreateSomething, action.payload); // call API here
    yield put(routine.success(response));
    yield call(goToItem, response); // navigating to new item
  catch (error) {
    yield put(routine.failure(error.message)); // or use SubmissionError as in README
  } finally {
    yield put(routine.fulfill());
  }
}

function* rootSaga() {
  yield takeEvery(routine.TRIGGER, createSomethingSaga);
}
```

**Comment by afitiskin** [comment]
Also, routine itself returns a promise, so for your example use `this.props.myRoutine().then()` instead of `this.props.myRoutine.trigger()`.

**Comment by alexhayes** [comment]
> Also, routine itself returns a promise, so for your example use this.props.myRoutine().then() instead of this.props.myRoutine.trigger().

Am I correct in thinking however that `this.props.myRoutine()` does not actually call `trigger` on the routine? It appears to just dispatch the action type `@@redux-saga-routines/PROMISE`.

**Comment by afitiskin** [comment]
You forgot to run `routinesWatcherSaga` to make this work. See preparation section in README

**Comment by alexhayes** [comment]
Thanks @afitiskin!
