### ISSUE TITLE
`routineStages` is actually exported as `defaultRoutineStages`

### ISSUE THREAD

**Issue by talor-hammond** [afitiskin/redux-saga-routines#63]
Had an issue trying to grab `routineStages` from `redux-saga-routines` like so...

```
import {  routineStages, ... } from 'redux-saga-routines'
// routineStages is not exported from...
```

This is how it is referenced in the documentation^

After some digging, I tried:
```
import { defaultRoutineStages } ...
```

And it worked :) I can make a PR to update the docs?

**Comment by afitiskin** [comment]
@talor-hammond thank you!
