### ISSUE TITLE
How to I can combine with redux-toolkit?

### ISSUE THREAD

**Issue by cuongdevjs** [afitiskin/redux-saga-routines#69]
I using redux-toolkit and I'm so really wanna integrate this package with redux-toolkit?

**Comment by shapkarin** [comment]
Did you try to use is like createAction? Looks like it's possible.

**Comment by cuongdevjs** [comment]
can you try it in code sandbox? Thanks so much :)

**Comment by shapkarin** [comment]
Not sure but I guess like that. Use routine types in reducer.
```js
const routine = createRoutine('example');

const counter = createReducer({ loading: false, result: {} }, {
  [routine]: (state) => ({ ...state, loading: true }).
  [routine. SUCCESS]: (state, payload) => ({ ...state, result: payload})
})
```

**Comment by cuongdevjs** [comment]
thanks for your help :)

**Comment by shapkarin** [comment]
@cuongdevjs cool then) maybe you found that useful too [extend-saga-routines](https://github.com/shapkarin/extend-saga-routines)

**Comment by cuongdevjs** [comment]
I tried this repo combine redux-toolkit, and it's not working. Can you help me?
store: 
````
const githubRepoFormSlice = createSlice({
  name: 'githubRepoForm',
  initialState,
  reducers: {
    changeUsername(state, action: PayloadAction<string>): any {
      state.username = action.payload;
    },
    [routine.REQUEST](state) {
      state.loading = true;
      state.error = null;
      state.repositories = [];
    },
    [routine.SUCCESS](state, action: PayloadAction<Repo[]>): any {
      const repos = action.payload;
      state.repositories = repos;
      state.loading = false;
    },
    [routine.FAILURE](state, action: PayloadAction<RepoErrorType>): any {
      state.error = action.payload;
      state.loading = false;
    },
  },
});
````
saga: `yield put(actions[routine.FAILURE](RepoErrorType.USERNAME_EMPTY));`

**Comment by shapkarin** [comment]
Not sure that it's related to `redux-saga-routines` itself but you can provide codesandbox and maybe I or someone can help you.

**Comment by shapkarin** [comment]
@cuongdevjs `redux-saga-routines` it's just some kind of smart action creator so you can use it pretty similar with any other action creators.

**Comment by cuongdevjs** [comment]
Thanks.
