### ISSUE TITLE
Routines without saga

### ISSUE THREAD

**Issue by shapkarin** [afitiskin/redux-saga-routines#70]
I wonder about this package without redux-saga dependency. In some cases we need to  decrease bundle size or people can have maybe other reasons to avoid redux-saga. How about to remove redux-saga dependency and move promise features to other package? I know, that all sounds like breaking changes... Or maybe I can copy this repo and make this kind of version?

What do you think about that proposal?

**Comment by shapkarin** [comment]
Actually I mostly need that to use https://github.com/shapkarin/extend-saga-routines without redux-saga sometimes.

**Comment by afitiskin** [comment]
I thought about it some time ago. But the name of the package tied us to `redux-saga` :)
And `redux-saga` is a peer dependency, so it's up to you: to use or not to use it. And bundle size may be reduced by proper tree-shaking and moving parts into separate files: we may use all related to saga to separate file, like `import { something } from 'redux-saga-routines/saga'`

**Comment by shapkarin** [comment]
So if we move all things about saga outside of main exports to separate file then `redux-saga` will become optional till we not import something from that files? Right?

**Comment by afitiskin** [comment]
It's already done btw, every part of the package lives in it's own file. So, just import from `redux-saga-routines/dist/something` (common js) or `redux-saga-routines/es/something` (es modules) and that's it!

**Comment by shapkarin** [comment]
Thanks. Maybe I will add some docs about that later. I will reopen an issue when I will be able to add that info.
Also feels free to reopen it too, if you are thinking to move redux outside of main imports. 
PS
maybe it’s a crazy idea but we also can create alias package with other name, like ‘routines’. Not sure about that at all.
