### ISSUE TITLE
Package improvements

### ISSUE THREAD

**Issue by onrige** [afitiskin/redux-saga-routines#8]
Hey. First thanks for your package, it's really helpful :)

But I write to offer some package improvements if you're interested in (I also can help with pull requests)

First, what do you think about hard dependence  on redux-saga? I think it would be cool if it was not (like an option for example). But next if some one will need these features like saga or form support - he can just enable it.

Another one is redux-actions functionality. What do you think if we just merge some common features like create and handle actions and in this case we will have a universal utility for creating simple actions, routine actions, actions handler, saga and form support and it will be all in one package?

So...just a conversation, thanks :)

**Comment by afitiskin** [comment]
@onrige

**Comment by afitiskin** [comment]
Reopen issue when you have some ideas
