### ISSUE TITLE
Is there a reason why this is tied to saga?

### ISSUE THREAD

**Issue by NateAGeek** [afitiskin/redux-saga-routines#81]
I'm thinking about using this library for my project. I was planning on using it with RxJS and redux-observable, as it would provide a good starting point for some of my async actions... The only issue is that I noticed this has "saga" in the title. Is this library really attached to using saga? Or could it be used for something else such as RxJS? If it is not tightly coupled with saga it might be worth updating the name to redux-action-routines?

**Comment by shapkarin** [comment]
@NateAGeek Hello! I have the same idea. Please have a check https://github.com/afitiskin/redux-saga-routines/issues/73

I has own package that used this one and plan to remove redux-saga https://github.com/shapkarin/extend-saga-routines

**Comment by shapkarin** [comment]
@NateAGeek done. please have a check https://github.com/shapkarin/extend-saga-routines (version 3.3.0)

**Comment by NateAGeek** [comment]
@shapkarin I do like the fact that you've taken initiative and created a separate package. A bit of feedback on your project.
* Also, the project title still has saga in it.
* Typing is not created for typescript
* Although you are making a big changes, I think it is fair to credit the author of this project for inspiration.

Good job all around, and I think I might use this in my project.
Thank you,
Nate

**Comment by NateAGeek** [comment]
Going to close now, but if the author, @afitiskin, could please comment on this, thank you.

**Comment by shapkarin** [comment]
> @shapkarin I do like the fact that you've taken initiative and created a separate package. A bit of feedback on your project.
> 
> * Also, the project title still has saga in it.
> * Typing is not created for typescript
> * Although you are making a big changes, I think it is fair to credit the author of this project for inspiration.
> 
> Good job all around, and I think I might use this in my project.
> Thank you,
> Nate

Of course. I also provide PR to this repo (check the PRs) and in docs I have a link to his package.
@NateAGeek can you help me with `Typing is not created for typescript` ?
`Also, the project title still has saga in it.` - maybe I will create an other package that uses my and just with new name

**Comment by shapkarin** [comment]
@NateAGeek https://www.npmjs.com/package/extend-routines
